import type { OntologyProject } from './types'

/**
 * 示例本体：供应商管理系统
 * 来源：《YCM-KH-MOMPF20-U010-22_MOM R2.0 供应商管理功能设计书》
 *
 * 业务范围：供应商集团建档 → 供应商注册（主子表 + 审批）→ 资质转合格 →
 *   ├─ 物料准入：供应商物料登记 → 物料转合格
 *   └─ 状态治理：状态变更申请 → 审批 →（冻结/解冻/失效）执行
 *        └─ 失效联动：供应商失效 → 名下物料级联失效（业务自洽补全）
 *   物料状态治理：物料状态变更申请 → 审批 →（冻结）执行
 *
 * 五模型覆盖：
 *   OBJ  供应商集团 / 供应商 / 供应商物料 / 供应商状态更新单 / 供应商物料状态更新单
 *   BHV  建档、注册、审批、转合格、状态变更、执行等原子操作
 *   EVT  贯穿全生命周期的领域事件（无环 DAG）
 *   RULE 纯规则：编码生成、唯一性、必填、默认账户唯一、安全库存范围、转合格拦截
 *   POLICY 事件驱动反应器：资质审核、物料准入、状态路由、定时冻结、失效级联
 *
 * 设计为无环 DAG，每个事件均至少有生产者；每条策略均有订阅与触发：
 *   预期校验结果为 0 错误 / 0 警告。
 */
export const supplierSampleProject: OntologyProject = {
  version: '1.0',
  name: '供应商管理系统',
  objects: [
    {
      id: 'SupplierGroup',
      name: '供应商集团',
      description: '供应商集团聚合根，统一管理集团工商与账户信息，供应商可绑定到集团',
      identity: 'groupCode',
      attributes: [
        { name: 'groupCode', type: 'string', required: true, description: '集团编码：G+4位流水，提交后生成' },
        { name: 'groupName', type: 'string', required: true, description: '集团名称' },
        { name: 'bankName', type: 'string', required: false, description: '开户行' },
        { name: 'bankAccount', type: 'string', required: false, description: '收款账户' },
        { name: 'employeeCount', type: 'number', required: false, description: '公司人数' },
        { name: 'contactAddress', type: 'string', required: false, description: '联系地址' },
        { name: 'taxpayerNo', type: 'string', required: false, description: '纳税人识别号' },
        { name: 'groupStatus', type: 'enum', required: false, description: '集团状态：存续1/注销2/吊销3/撤销4/破产5/重整6' },
        { name: 'establishDate', type: 'date', required: false, description: '成立时间' },
        { name: 'legalPerson', type: 'string', required: false, description: '法定代表人' },
        { name: 'registeredCapital', type: 'decimal', required: false, description: '注册资本(万元)' },
        { name: 'paidInCapital', type: 'decimal', required: false, description: '实缴资本(万元)' },
        { name: 'enterpriseNature', type: 'enum', required: false, description: '企业性质：国有1/民营2/外资3/合作社4/集体5/个体6/药品经营7' },
        { name: 'licenseNo', type: 'string', required: false, description: '营业执照编号' },
        { name: 'businessScope', type: 'string', required: false, description: '经营范围' },
        { name: 'registeredAddress', type: 'string', required: false, description: '注册地址' },
        { name: 'businessInfoUpdateTime', type: 'datetime', required: false, description: '工商信息更新时间' },
        { name: 'remark', type: 'string', required: false, description: '备注' },
        { name: 'discarded', type: 'boolean', required: true, description: '废弃标记（隐藏域）' },
      ],
      entities: [],
      valueObjects: [],
      invariants: [
        { id: 'inv_group_code', expression: 'groupCode != null && unique(groupCode)', description: '集团编码非空且全局唯一' },
      ],
      references: [],
    },
    {
      id: 'Supplier',
      name: '供应商',
      description: '供应商聚合根（主子表），覆盖注册、审批、信息更新留痕与四态生命周期（临时/合格/冻结/失效）',
      identity: 'supplierCode',
      attributes: [
        { name: 'supplierCode', type: 'string', required: true, description: '供应商编码：国家代码+4位流水，提交后生成' },
        { name: 'supplierName', type: 'string', required: true, description: '供应商名称' },
        { name: 'supplierShortName', type: 'string', required: true, description: '供应商简称' },
        { name: 'supplierCategory', type: 'enum', required: true, description: '供应商分类：集团内1/集团外2' },
        { name: 'supplierType', type: 'enum', required: true, description: '供应商类型：原材料1/非原材料2' },
        { name: 'goodsCategory', type: 'enum', required: true, description: '商品分类：化学品1/副资材2' },
        { name: 'country', type: 'enum', required: true, description: '国家/地区：CN中国/JP日本/US美国' },
        { name: 'groupCode', type: 'reference', required: false, description: '所属集团（引用 SupplierGroup）' },
        { name: 'industry', type: 'enum', required: false, description: '所属行业：制造业1/物流业2…' },
        { name: 'postalCode', type: 'string', required: false, description: '邮政编码' },
        { name: 'contactAddress', type: 'string', required: false, description: '联系地址' },
        { name: 'phone', type: 'string', required: false, description: '电话' },
        { name: 'email', type: 'string', required: false, description: 'Email地址' },
        { name: 'annualRevenue', type: 'decimal', required: false, description: '年营收' },
        { name: 'employeeCount', type: 'number', required: false, description: '公司人数' },
        { name: 'taxRate', type: 'decimal', required: false, description: '税率(%)' },
        { name: 'creditLevel', type: 'string', required: false, description: '信用等级' },
        { name: 'creditLimit', type: 'decimal', required: false, description: '信用额度' },
        { name: 'creditPeriod', type: 'string', required: false, description: '信用期限' },
        { name: 'settlementMethod', type: 'enum', required: false, description: '结算方式：转账支票1/现金支票2…' },
        { name: 'paymentCondition', type: 'string', required: false, description: '付款条件' },
        { name: 'currency', type: 'enum', required: false, description: '币种：RMB人民币/JPY日元/USD美元' },
        { name: 'deliveryMethod', type: 'enum', required: false, description: '到货方式：送到工厂1/送到工厂含卸货2' },
        { name: 'deliveryWarehouse', type: 'string', required: false, description: '到货仓库（主数据）' },
        { name: 'tradeMethod', type: 'enum', required: false, description: '贸易方式：一般贸易1/加工贸易2…' },
        { name: 'tradeTerms', type: 'enum', required: false, description: '交易条款：EXW/FOB' },
        { name: 'qualityRequirement', type: 'string', required: false, description: '品质要求' },
        { name: 'initiator', type: 'string', required: false, description: '发起人（当前登录账号）' },
        { name: 'firstApprover', type: 'string', required: true, description: '一级审批' },
        { name: 'secondApprover', type: 'string', required: true, description: '二级审批' },
        { name: 'oldSupplierId', type: 'reference', required: false, description: '旧供应商ID：信息更新留痕，指向上一版（自引用）' },
        { name: 'supplierStatus', type: 'enum', required: true, description: '供应商状态：临时0/合格1/冻结2/失效3（隐藏域）' },
        { name: 'discarded', type: 'boolean', required: true, description: '废弃标记（隐藏域）' },
      ],
      entities: [
        {
          id: 'BankAccount',
          name: '银行账户信息',
          identity: 'bankAccountNo',
          attributes: [
            { name: 'bankAccountNo', type: 'string', required: true, description: '银行账号' },
            { name: 'accountName', type: 'string', required: true, description: '账户名称' },
            { name: 'bankName', type: 'string', required: false, description: '开户银行' },
            { name: 'isDefault', type: 'boolean', required: true, description: '是否默认（多明细仅一条为默认）' },
            { name: 'belongBank', type: 'string', required: false, description: '所属银行' },
            { name: 'bankLineNo', type: 'string', required: false, description: '行号' },
          ],
        },
        {
          id: 'SupplierContact',
          name: '供应商联系人',
          identity: 'seq',
          attributes: [
            { name: 'seq', type: 'number', required: true, description: '序号' },
            { name: 'contactName', type: 'string', required: true, description: '联系姓名' },
            { name: 'contactPhone', type: 'string', required: false, description: '联系电话' },
            { name: 'contactMobile', type: 'string', required: false, description: '联系手机' },
            { name: 'contactEmail', type: 'string', required: false, description: '联系邮箱' },
            { name: 'department', type: 'string', required: false, description: '部门' },
            { name: 'position', type: 'string', required: false, description: '职级' },
          ],
        },
        {
          id: 'QualificationCert',
          name: '供应商资格证书',
          identity: 'certName',
          attributes: [
            { name: 'certName', type: 'string', required: true, description: '证书名称' },
            { name: 'certType', type: 'enum', required: false, description: '证书类别：安全生产许可证1/企业资质证2' },
            { name: 'attachment', type: 'string', required: false, description: '附件' },
            { name: 'expireDate', type: 'date', required: false, description: '到期时间' },
          ],
        },
        {
          id: 'SupplierAgreement',
          name: '供应商签订协议',
          identity: 'agreementName',
          attributes: [
            { name: 'agreementName', type: 'string', required: true, description: '协议名称' },
            { name: 'agreementDate', type: 'date', required: false, description: '协议日期' },
            { name: 'attachment', type: 'string', required: false, description: '附件' },
            { name: 'uploadDate', type: 'date', required: false, description: '上传日期（当前日期）' },
            { name: 'agreementType', type: 'enum', required: false, description: '协议类别：采购1/保密2…' },
          ],
        },
      ],
      valueObjects: [
        {
          id: 'BusinessRegistrationInfo',
          name: '工商信息',
          attributes: [
            { name: 'enterpriseStatus', type: 'enum', required: false, description: '企业状态：存续1/注销2/吊销3/撤销4/破产5/重整6' },
            { name: 'establishDate', type: 'date', required: false, description: '成立时间' },
            { name: 'legalPerson', type: 'string', required: false, description: '法定代表人' },
            { name: 'registeredCapital', type: 'decimal', required: false, description: '注册资本(万元)' },
            { name: 'paidInCapital', type: 'decimal', required: false, description: '实缴资本(万元)' },
            { name: 'enterpriseNature', type: 'enum', required: false, description: '企业性质：国有1/民营2/外资3…' },
            { name: 'enterpriseType', type: 'enum', required: false, description: '企业类型：有限责任1/股份有限2…' },
            { name: 'licenseNo', type: 'string', required: false, description: '营业执照编号' },
            { name: 'taxpayerNo', type: 'string', required: false, description: '纳税人登记号' },
            { name: 'registeredAddress', type: 'string', required: false, description: '注册地址' },
            { name: 'businessScope', type: 'string', required: false, description: '经营范围' },
            { name: 'businessInfoUpdateTime', type: 'datetime', required: false, description: '工商信息更新时间' },
          ],
        },
      ],
      invariants: [
        { id: 'inv_supplier_code', expression: 'supplierCode != null && unique(supplierCode)', description: '供应商编码非空且全局唯一' },
        { id: 'inv_default_bank', expression: 'count(bankAccounts where isDefault == true) <= 1', description: '银行账户至多一条默认' },
        { id: 'inv_supplier_status', expression: 'supplierStatus in {0,1,2,3}', description: '供应商状态仅限 临时/合格/冻结/失效' },
        { id: 'inv_supplier_required', expression: 'supplierName != null && supplierShortName != null', description: '供应商名称与简称必填' },
      ],
      references: [
        { targetObjectId: 'SupplierGroup', refField: 'groupCode', description: '供应商绑定到集团' },
        { targetObjectId: 'Supplier', refField: 'oldSupplierId', description: '信息更新留痕：指向被替换的上一版供应商' },
      ],
    },
    {
      id: 'SupplierMaterial',
      name: '供应商物料',
      description: '供应商可采购物料聚合根，承载采购参数与四态生命周期（临时/合格/冻结/失效）',
      identity: 'lineId',
      attributes: [
        { name: 'lineId', type: 'string', required: true, description: '供应商物料行ID' },
        { name: 'materialCode', type: 'string', required: true, description: '物料编码（物料主数据带入）' },
        { name: 'materialName', type: 'string', required: false, description: '物料名称' },
        { name: 'specModel', type: 'string', required: false, description: '规格型号' },
        { name: 'materialType', type: 'enum', required: false, description: '物料类型（主数据）' },
        { name: 'category1', type: 'enum', required: false, description: '一级分类（物料分类主数据）' },
        { name: 'category2', type: 'enum', required: false, description: '二级分类（物料分类主数据）' },
        { name: 'category3', type: 'enum', required: false, description: '三级分类（物料分类主数据）' },
        { name: 'unit', type: 'enum', required: false, description: '单位（主数据）' },
        { name: 'supplierCode', type: 'reference', required: true, description: '所属供应商（引用 Supplier）' },
        { name: 'supplierName', type: 'string', required: false, description: '供应商名称（冗余展示）' },
        { name: 'productName', type: 'string', required: true, description: '商品名称' },
        { name: 'tagName', type: 'string', required: false, description: '标签名' },
        { name: 'shelfCondition', type: 'string', required: false, description: '保质条件' },
        { name: 'minContainQty', type: 'number', required: false, description: '最小收容数' },
        { name: 'minDeliveryQty', type: 'number', required: false, description: '最小送货量' },
        { name: 'purchaseRatio', type: 'decimal', required: false, description: '采购比例(%)' },
        { name: 'purchaseCycle', type: 'number', required: false, description: '采购周期(日)' },
        { name: 'safetyStockMonths', type: 'number', required: false, description: '安全在库月数（最大120）' },
        { name: 'remark', type: 'string', required: false, description: '备注' },
        { name: 'materialStatus', type: 'enum', required: true, description: '物料状态：临时0/合格1/冻结2/失效3（隐藏域）' },
        { name: 'discarded', type: 'boolean', required: true, description: '废弃标记（隐藏域）' },
      ],
      entities: [],
      valueObjects: [],
      invariants: [
        { id: 'inv_material_unique', expression: 'unique(supplierCode, materialCode)', description: '同一供应商下物料编码唯一' },
        { id: 'inv_safety_stock', expression: 'safetyStockMonths >= 0 && safetyStockMonths <= 120', description: '安全在库月数范围 0~120' },
        { id: 'inv_material_status', expression: 'materialStatus in {0,1,2,3}', description: '物料状态仅限 临时/合格/冻结/失效' },
      ],
      references: [
        { targetObjectId: 'Supplier', refField: 'supplierCode', description: '物料归属供应商' },
      ],
    },
    {
      id: 'SupplierStatusUpdate',
      name: '供应商状态更新单',
      description: '供应商状态变更单据（主子表），审批通过后按类型更新供应商状态；支持冻结的定时生效',
      identity: 'docNo',
      attributes: [
        { name: 'docNo', type: 'string', required: true, description: '单据编号' },
        { name: 'operator', type: 'string', required: true, description: '操作人（当前用户）' },
        { name: 'operateTime', type: 'datetime', required: true, description: '操作时间（当前时间）' },
        { name: 'targetStatus', type: 'enum', required: true, description: '变更类型/目标状态：临时0/合格1/冻结2/失效3' },
        { name: 'startTime', type: 'datetime', required: false, description: '冻结开始时间（区间内即时、否则定时生效）' },
        { name: 'endTime', type: 'datetime', required: false, description: '冻结结束时间' },
        { name: 'attachment', type: 'string', required: false, description: '附件' },
        { name: 'reason', type: 'string', required: false, description: '原因' },
        { name: 'remark', type: 'string', required: false, description: '备注' },
        { name: 'firstApprover', type: 'string', required: true, description: '一级审批' },
        { name: 'secondApprover', type: 'string', required: true, description: '二级审批' },
        { name: 'approvalStatus', type: 'enum', required: true, description: '审批状态' },
        { name: 'isCancel', type: 'boolean', required: true, description: '是否取消（取消冻结回退至冻结前状态）' },
      ],
      entities: [
        {
          id: 'SupplierStatusLine',
          name: '状态更新明细',
          identity: 'supplierCode',
          attributes: [
            { name: 'supplierCode', type: 'string', required: true, description: '供应商编码' },
            { name: 'supplierName', type: 'string', required: false, description: '供应商名称' },
            { name: 'supplierType', type: 'enum', required: false, description: '供应商类型' },
            { name: 'supplierCategory', type: 'enum', required: false, description: '供应商分类' },
            { name: 'groupCode', type: 'string', required: false, description: '集团' },
            { name: 'supplierId', type: 'string', required: false, description: '供应商ID（隐藏域）' },
            { name: 'currentStatus', type: 'enum', required: false, description: '当前状态（隐藏域）' },
            { name: 'isCancel', type: 'boolean', required: false, description: '是否取消（隐藏域）' },
          ],
        },
      ],
      valueObjects: [],
      invariants: [
        { id: 'inv_status_doc', expression: 'docNo != null && count(lines) >= 1', description: '单据编号非空且至少一条明细' },
      ],
      references: [],
    },
    {
      id: 'MaterialStatusUpdate',
      name: '供应商物料状态更新单',
      description: '供应商物料状态变更单据（主子表），审批通过后按类型更新物料状态',
      identity: 'docNo',
      attributes: [
        { name: 'docNo', type: 'string', required: true, description: '单据编号' },
        { name: 'operator', type: 'string', required: true, description: '操作人（当前用户）' },
        { name: 'operateTime', type: 'datetime', required: true, description: '操作时间（当前时间）' },
        { name: 'targetStatus', type: 'enum', required: true, description: '变更类型/目标状态：临时0/合格1/冻结2/失效3' },
        { name: 'attachment', type: 'string', required: false, description: '附件' },
        { name: 'reason', type: 'string', required: false, description: '原因' },
        { name: 'remark', type: 'string', required: false, description: '备注' },
        { name: 'firstApprover', type: 'string', required: false, description: '一级审批' },
        { name: 'secondApprover', type: 'string', required: false, description: '二级审批' },
        { name: 'approvalStatus', type: 'enum', required: true, description: '审批状态' },
        { name: 'isCancel', type: 'boolean', required: true, description: '是否取消（取消冻结回退至冻结前状态）' },
      ],
      entities: [
        {
          id: 'MaterialStatusLine',
          name: '物料状态更新明细',
          identity: 'materialCode',
          attributes: [
            { name: 'materialCode', type: 'string', required: true, description: '物料编码' },
            { name: 'materialName', type: 'string', required: false, description: '物料名称' },
            { name: 'specModel', type: 'string', required: false, description: '规格型号' },
            { name: 'materialType', type: 'enum', required: false, description: '物料类型' },
            { name: 'supplierCode', type: 'string', required: false, description: '供应商编码' },
            { name: 'supplierName', type: 'string', required: false, description: '供应商名称' },
            { name: 'productName', type: 'string', required: false, description: '商品名称' },
            { name: 'materialId', type: 'string', required: false, description: '供应商物料ID（隐藏域）' },
            { name: 'currentStatus', type: 'enum', required: false, description: '当前状态（隐藏域）' },
            { name: 'isCancel', type: 'boolean', required: false, description: '是否取消（隐藏域）' },
          ],
        },
      ],
      valueObjects: [],
      invariants: [
        { id: 'inv_mat_status_doc', expression: 'docNo != null && count(lines) >= 1', description: '单据编号非空且至少一条明细' },
      ],
      references: [],
    },
  ],
  behaviors: [
    {
      id: 'CreateSupplierGroup',
      name: '创建供应商集团',
      description: '维护集团工商与账户信息，提交即生成集团编码（G+4位流水，当前最大编码加1）',
      objectRef: 'SupplierGroup',
      preconditions: ['集团名称非空'],
      postconditions: ['生成集团编码', '集团建档完成'],
      appliedRuleRefs: ['GroupCodeGenRule'],
      producedEventRefs: ['GroupRegistered'],
      subscribedEventRefs: [],
    },
    {
      id: 'RegisterSupplier',
      name: '注册供应商',
      description: '录入供应商主子表（银行账户/联系人/资格证书/签订协议），启动两级审批流',
      objectRef: 'Supplier',
      preconditions: ['名称/简称/分类/类型/商品分类/国家 必填', '银行账户至多一条默认'],
      postconditions: ['生成供应商编码', '供应商进入审批中'],
      appliedRuleRefs: ['SupplierCodeGenRule', 'DefaultBankAccountRule', 'SupplierCodeUniqueRule'],
      producedEventRefs: ['SupplierSubmitted'],
      subscribedEventRefs: [],
    },
    {
      id: 'ApproveSupplier',
      name: '审批供应商注册',
      description: '一级、二级审批通过后，供应商状态置为「临时」',
      objectRef: 'Supplier',
      preconditions: ['供应商处于审批中'],
      postconditions: ['供应商状态置为临时'],
      appliedRuleRefs: ['SupplierInfoCompleteRule'],
      producedEventRefs: ['SupplierRegistered'],
      subscribedEventRefs: ['SupplierSubmitted'],
    },
    {
      id: 'QualifySupplier',
      name: '转合格供应商',
      description: '资质审核通过或转合格审批通过后，供应商状态置为「合格」',
      objectRef: 'Supplier',
      preconditions: ['供应商为临时/冻结前状态', '非已合格'],
      postconditions: ['供应商状态置为合格'],
      appliedRuleRefs: [],
      producedEventRefs: ['SupplierQualified'],
      subscribedEventRefs: ['SupplierApprovedForQualify'],
    },
    {
      id: 'RegisterMaterial',
      name: '登记供应商物料',
      description: '基于合格供应商登记可采购物料，校验「供应商+物料」唯一与安全库存范围',
      objectRef: 'SupplierMaterial',
      preconditions: ['供应商为合格状态', '供应商+物料编码不重复'],
      postconditions: ['生成供应商物料', '物料状态置为临时'],
      appliedRuleRefs: ['MaterialUniqueRule', 'SafetyStockRule'],
      producedEventRefs: ['MaterialRegistered'],
      subscribedEventRefs: ['MaterialOnboardingEnabled'],
    },
    {
      id: 'QualifyMaterial',
      name: '转合格物料',
      description: '物料资质审核通过后，物料状态置为「合格」',
      objectRef: 'SupplierMaterial',
      preconditions: ['物料为临时状态', '非已合格'],
      postconditions: ['物料状态置为合格'],
      appliedRuleRefs: [],
      producedEventRefs: ['MaterialQualified'],
      subscribedEventRefs: ['MaterialApprovedForQualify'],
    },
    {
      id: 'SubmitSupplierStatusChange',
      name: '提交供应商状态变更',
      description: '基于供应商列表发起冻结/失效/转合格/取消冻结申请，启动审批流',
      objectRef: 'SupplierStatusUpdate',
      preconditions: ['已选择供应商', '转合格时供应商非已合格'],
      postconditions: ['生成状态更新单', '进入审批中'],
      appliedRuleRefs: ['AlreadyQualifiedRule'],
      producedEventRefs: ['SupplierStatusChangeSubmitted'],
      subscribedEventRefs: [],
    },
    {
      id: 'ApproveSupplierStatusChange',
      name: '审批供应商状态变更',
      description: '两级审批通过后，由策略按变更类型路由到对应执行动作',
      objectRef: 'SupplierStatusUpdate',
      preconditions: ['状态更新单处于审批中'],
      postconditions: ['审批通过，待执行'],
      appliedRuleRefs: [],
      producedEventRefs: ['SupplierStatusChangeApproved'],
      subscribedEventRefs: ['SupplierStatusChangeSubmitted'],
    },
    {
      id: 'ExecuteSupplierFreeze',
      name: '执行供应商冻结',
      description: '冻结生效（区间内即时、否则定时任务触发），供应商状态置为「冻结」',
      objectRef: 'Supplier',
      preconditions: ['冻结申请已审批'],
      postconditions: ['供应商状态置为冻结', '记录冻结前状态'],
      appliedRuleRefs: [],
      producedEventRefs: ['SupplierFrozen'],
      subscribedEventRefs: ['SupplierFreezeDue'],
    },
    {
      id: 'ExecuteSupplierUnfreeze',
      name: '执行供应商解冻',
      description: '取消冻结，供应商状态回退至冻结前状态',
      objectRef: 'Supplier',
      preconditions: ['供应商为冻结状态'],
      postconditions: ['供应商状态回退至冻结前', '冻结操作标记取消'],
      appliedRuleRefs: [],
      producedEventRefs: ['SupplierUnfrozen'],
      subscribedEventRefs: ['SupplierUnfreezeDue'],
    },
    {
      id: 'ExecuteSupplierInvalidate',
      name: '执行供应商失效',
      description: '失效生效（区间内即时、否则定时任务触发），供应商状态置为「失效」',
      objectRef: 'Supplier',
      preconditions: ['失效申请已审批'],
      postconditions: ['供应商状态置为失效'],
      appliedRuleRefs: [],
      producedEventRefs: ['SupplierInvalidated'],
      subscribedEventRefs: ['SupplierInvalidateDue'],
    },
    {
      id: 'CascadeInvalidateMaterial',
      name: '级联失效供应商物料',
      description: '业务自洽补全：供应商失效时，名下在用物料一并失效',
      objectRef: 'SupplierMaterial',
      preconditions: ['所属供应商已失效'],
      postconditions: ['名下物料状态置为失效'],
      appliedRuleRefs: [],
      producedEventRefs: ['MaterialInvalidated'],
      subscribedEventRefs: ['MaterialCascadeInvalidate'],
    },
    {
      id: 'SubmitMaterialStatusChange',
      name: '提交物料状态变更',
      description: '基于供应商物料列表发起冻结/失效/转合格/取消冻结申请，启动审批流',
      objectRef: 'MaterialStatusUpdate',
      preconditions: ['已选择物料', '转合格时物料非已合格'],
      postconditions: ['生成物料状态更新单', '进入审批中'],
      appliedRuleRefs: ['MaterialAlreadyQualifiedRule'],
      producedEventRefs: ['MaterialStatusChangeSubmitted'],
      subscribedEventRefs: [],
    },
    {
      id: 'ApproveMaterialStatusChange',
      name: '审批物料状态变更',
      description: '两级审批通过后，由策略按变更类型路由到对应执行动作',
      objectRef: 'MaterialStatusUpdate',
      preconditions: ['物料状态更新单处于审批中'],
      postconditions: ['审批通过，待执行'],
      appliedRuleRefs: [],
      producedEventRefs: ['MaterialStatusChangeApproved'],
      subscribedEventRefs: ['MaterialStatusChangeSubmitted'],
    },
    {
      id: 'ExecuteMaterialFreeze',
      name: '执行物料冻结',
      description: '冻结生效，供应商物料状态置为「冻结」',
      objectRef: 'SupplierMaterial',
      preconditions: ['冻结申请已审批'],
      postconditions: ['物料状态置为冻结', '记录冻结前状态'],
      appliedRuleRefs: [],
      producedEventRefs: ['MaterialFrozen'],
      subscribedEventRefs: ['MaterialFreezeDue'],
    },
  ],
  events: [
    {
      id: 'GroupRegistered',
      name: '集团已建档',
      payload: [{ name: 'groupCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierSubmitted',
      name: '供应商注册已提交',
      payload: [
        { name: 'supplierCode', type: 'string', required: true },
        { name: 'initiator', type: 'string', required: true },
      ],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierRegistered',
      name: '供应商注册完成',
      description: '审批通过，供应商进入「临时」状态',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierApprovedForQualify',
      name: '供应商资质审核通过',
      description: '由资质审核策略或转合格审批策略触发',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierQualified',
      name: '供应商已转合格',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialOnboardingEnabled',
      name: '供应商物料准入已开通',
      description: '合格供应商可登记可采购物料',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialRegistered',
      name: '供应商物料已登记',
      payload: [
        { name: 'supplierCode', type: 'string', required: true },
        { name: 'materialCode', type: 'string', required: true },
      ],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialApprovedForQualify',
      name: '物料资质审核通过',
      payload: [{ name: 'lineId', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialQualified',
      name: '供应商物料已转合格',
      payload: [{ name: 'lineId', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierStatusChangeSubmitted',
      name: '供应商状态变更已提交',
      payload: [
        { name: 'docNo', type: 'string', required: true },
        { name: 'targetStatus', type: 'enum', required: true },
      ],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierStatusChangeApproved',
      name: '供应商状态变更已审批',
      description: '审批通过，按 targetStatus 路由到冻结/解冻/失效/转合格',
      payload: [
        { name: 'docNo', type: 'string', required: true },
        { name: 'targetStatus', type: 'enum', required: true },
      ],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'SupplierFreezeDue',
      name: '供应商冻结到期生效',
      description: '区间内即时、否则由定时任务在开始时间触发',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'SupplierUnfreezeDue',
      name: '供应商解冻生效',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'SupplierInvalidateDue',
      name: '供应商失效生效',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'SupplierFrozen',
      name: '供应商已冻结',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierUnfrozen',
      name: '供应商已解冻',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'SupplierInvalidated',
      name: '供应商已失效',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialCascadeInvalidate',
      name: '物料联动失效指令',
      description: '供应商失效触发名下物料级联失效',
      payload: [{ name: 'supplierCode', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialInvalidated',
      name: '供应商物料已失效',
      payload: [{ name: 'lineId', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialStatusChangeSubmitted',
      name: '物料状态变更已提交',
      payload: [
        { name: 'docNo', type: 'string', required: true },
        { name: 'targetStatus', type: 'enum', required: true },
      ],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
    {
      id: 'MaterialStatusChangeApproved',
      name: '物料状态变更已审批',
      payload: [
        { name: 'docNo', type: 'string', required: true },
        { name: 'targetStatus', type: 'enum', required: true },
      ],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'MaterialFreezeDue',
      name: '物料冻结生效',
      payload: [{ name: 'lineId', type: 'string', required: true }],
      deliverySemantics: 'EXACTLY_ONCE',
    },
    {
      id: 'MaterialFrozen',
      name: '供应商物料已冻结',
      payload: [{ name: 'lineId', type: 'string', required: true }],
      deliverySemantics: 'AT_LEAST_ONCE',
    },
  ],
  rules: [
    {
      id: 'GroupCodeGenRule',
      name: '集团编码生成规则',
      description: '计算规则：集团编码 = "G" + 4位流水（当前集团表最大编码加1）',
      type: 'calculation',
      condition: 'groupCode = "G" + pad(max(existing.groupCode.serial) + 1, 4)',
    },
    {
      id: 'SupplierCodeGenRule',
      name: '供应商编码生成规则',
      description: '计算规则：供应商编码 = 国家代码 + 4位流水（当前供应商表最大编码加1）',
      type: 'calculation',
      condition: 'supplierCode = country + pad(max(existing.supplierCode.serial) + 1, 4)',
    },
    {
      id: 'SupplierCodeUniqueRule',
      name: '供应商编码唯一校验',
      description: '校验规则：供应商编码不可重复（导入/新增均拦截）',
      type: 'validation',
      condition: 'unique(Supplier.supplierCode)',
    },
    {
      id: 'DefaultBankAccountRule',
      name: '默认银行账户唯一校验',
      description: '校验规则：银行账户子表至多一条默认，否则拦截提示',
      type: 'validation',
      condition: 'count(bankAccounts where isDefault == true) <= 1',
    },
    {
      id: 'SupplierInfoCompleteRule',
      name: '供应商必填项校验',
      description: '校验规则：名称/简称/分类/类型/商品分类/国家 必填',
      type: 'validation',
      condition: 'supplierName && supplierShortName && supplierCategory && supplierType && goodsCategory && country',
    },
    {
      id: 'MaterialUniqueRule',
      name: '供应商物料唯一校验',
      description: '校验规则：同一供应商下「供应商编码+物料编码」不可重复',
      type: 'validation',
      condition: 'unique(SupplierMaterial.supplierCode + SupplierMaterial.materialCode)',
    },
    {
      id: 'SafetyStockRule',
      name: '安全在库月数范围校验',
      description: '校验规则：安全在库月数取值范围 0~120',
      type: 'validation',
      condition: 'safetyStockMonths >= 0 && safetyStockMonths <= 120',
    },
    {
      id: 'AlreadyQualifiedRule',
      name: '供应商转合格拦截',
      description: '校验规则：转合格时若供应商已是合格状态则拦截',
      type: 'validation',
      condition: 'targetStatus == 合格 ? supplierStatus != 合格 : true',
    },
    {
      id: 'MaterialAlreadyQualifiedRule',
      name: '物料转合格拦截',
      description: '校验规则：转合格时若物料已是合格状态则拦截',
      type: 'validation',
      condition: 'targetStatus == 合格 ? materialStatus != 合格 : true',
    },
  ],
  policies: [
    {
      id: 'QualificationReviewPolicy',
      name: '供应商资质审核策略',
      description: '事件驱动策略：注册完成后审核资质（证书有效、协议齐全），通过则进入转合格',
      subscribedEventRefs: ['SupplierRegistered'],
      condition: '资格证书均在有效期内 且 必备协议齐全',
      triggeredEventRefs: ['SupplierApprovedForQualify'],
    },
    {
      id: 'SupplierQualifyPolicy',
      name: '供应商转合格路由策略',
      description: '事件驱动策略：状态变更审批通过且类型为「转合格」时，路由到转合格执行',
      subscribedEventRefs: ['SupplierStatusChangeApproved'],
      condition: 'targetStatus == 合格',
      triggeredEventRefs: ['SupplierApprovedForQualify'],
    },
    {
      id: 'MaterialOnboardingPolicy',
      name: '物料准入开通策略',
      description: '事件驱动策略：供应商转合格后，开通其可采购物料登记入口',
      subscribedEventRefs: ['SupplierQualified'],
      condition: '供应商状态为合格',
      triggeredEventRefs: ['MaterialOnboardingEnabled'],
    },
    {
      id: 'MaterialReviewPolicy',
      name: '物料资质审核策略',
      description: '事件驱动策略：物料登记后审核，通过则进入物料转合格',
      subscribedEventRefs: ['MaterialRegistered'],
      condition: '物料主数据齐全 且 采购参数合规',
      triggeredEventRefs: ['MaterialApprovedForQualify'],
    },
    {
      id: 'SupplierFreezePolicy',
      name: '供应商冻结调度策略',
      description: '事件驱动策略：类型为「冻结」时调度生效——区间内即时、否则按开始时间定时触发',
      subscribedEventRefs: ['SupplierStatusChangeApproved'],
      condition: 'targetStatus == 冻结（now ∈ [startTime,endTime] 即时，否则定时）',
      triggeredEventRefs: ['SupplierFreezeDue'],
    },
    {
      id: 'SupplierUnfreezePolicy',
      name: '供应商解冻路由策略',
      description: '事件驱动策略：类型为「取消冻结」时，路由到解冻执行并回退至冻结前状态',
      subscribedEventRefs: ['SupplierStatusChangeApproved'],
      condition: 'targetStatus == 取消冻结',
      triggeredEventRefs: ['SupplierUnfreezeDue'],
    },
    {
      id: 'SupplierInvalidatePolicy',
      name: '供应商失效调度策略',
      description: '事件驱动策略：类型为「失效」时调度生效——区间内即时、否则按开始时间定时触发',
      subscribedEventRefs: ['SupplierStatusChangeApproved'],
      condition: 'targetStatus == 失效（now ≥ startTime 即时，否则定时）',
      triggeredEventRefs: ['SupplierInvalidateDue'],
    },
    {
      id: 'MaterialCascadePolicy',
      name: '供应商失效物料级联策略',
      description: '事件驱动策略：供应商失效时，联动其名下在用物料级联失效',
      subscribedEventRefs: ['SupplierInvalidated'],
      condition: '存在状态非失效的名下物料',
      triggeredEventRefs: ['MaterialCascadeInvalidate'],
    },
    {
      id: 'MaterialFreezePolicy',
      name: '物料冻结路由策略',
      description: '事件驱动策略：物料状态变更审批通过且类型为「冻结」时，路由到物料冻结执行',
      subscribedEventRefs: ['MaterialStatusChangeApproved'],
      condition: 'targetStatus == 冻结',
      triggeredEventRefs: ['MaterialFreezeDue'],
    },
  ],
}
